---
- hosts: localhost
  tasks:
    - name: ensure .config directory exist
      file:
        path: "~/.config"
        state: directory
    - name: symlink neovim settings
      file:
        src: "{{ playbook_dir }}/nvim"
        dest: "~/.config/nvim"
        state: link
        force: yes
    - name: symlink fish settings
      file:
        src: "{{ playbook_dir }}/fish"
        dest: "~/.config/fish"
        state: link
        force: yes
    - name: symlink duti settings
      file:
        src: "{{ playbook_dir }}/duti/.duti"
        dest: "~/.duti"
        state: link
        force: yes
    - name: symlink tig settings
      file:
        src: "{{ playbook_dir }}/tig/.tigrc"
        dest: "~/.tigrc"
        state: link
        force: yes
    - name: clone repo with base16 colorscheme
      git:
        repo: "https://github.com/chriskempson/base16-shell.git"
        dest: "~/.config/base16-shell"
