---
- hosts: localhost
  tasks:
    - name: ensure .config directory exist
      file:
        path: "~/.config"
        state: directory
    - name: symlink neovim settings
      file:
        src: "{{ playbook_dir }}/nvim"
        dest: "~/.config/nvim"
        state: link
        force: yes
    - name: clone repo with base16 colorscheme
      git:
        repo: "https://github.com/chriskempson/base16-shell.git"
        dest: "~/.config/base16-shell"
